// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAFTsIRlDInzTzgPT1AbwiB4wDqwmrwuhc',
//     appId: '1:350505588729:android:46c3f94599240eb80f8f28',
//     messagingSenderId: '350505588729',
//     projectId: 'chat-app-firebase-based',
//     storageBucket: 'chat-app-firebase-based.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyD6d5qBGq5XTNLwe7QcOLCZlgZhyn9XvzQ',
//     appId: '1:350505588729:ios:1128f0545d3c4eb20f8f28',
//     messagingSenderId: '350505588729',
//     projectId: 'chat-app-firebase-based',
//     storageBucket: 'chat-app-firebase-based.firebasestorage.app',
//     iosBundleId: 'com.example.chatAppFlutter',
//   );

// }
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // Return the web configuration here
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyA6zWhWvRReA5L_E9za4PAguKbgPv2pzjM",
    authDomain: "chat-app-firebase-based.firebaseapp.com",
    projectId: "chat-app-firebase-based",
    storageBucket: "chat-app-firebase-based.firebasestorage.app",
    messagingSenderId: "350505588729",
    appId: "1:350505588729:web:4aa47060523e19eb0f8f28",
    measurementId: "G-D97ZCH5N5B" // Optional
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFTsIRlDInzTzgPT1AbwiB4wDqwmrwuhc',
    appId: '1:350505588729:android:46c3f94599240eb80f8f28',
    messagingSenderId: '350505588729',
    projectId: 'chat-app-firebase-based',
    storageBucket: 'chat-app-firebase-based.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6d5qBGq5XTNLwe7QcOLCZlgZhyn9XvzQ',
    appId: '1:350505588729:ios:1128f0545d3c4eb20f8f28',
    messagingSenderId: '350505588729',
    projectId: 'chat-app-firebase-based',
    storageBucket: 'chat-app-firebase-based.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFlutter',
  );
}
